const Categories = [
  {
    title: "valampuri hotel",
    price: 23,
    category: "jaffna",
    src: "/Images/hotel1.jpg",
    mapSrc: "https://goo.gl/maps/FguD2k2U2h54kqDX8",
  },
  {
    title: "north gate hotel",
    price: 23,
    category: "jaffna",
    src: "/Images/img11.jpeg",
    mapSrc: "https://goo.gl/maps/ze21KjevjBkmueGE9",
  },
  {
    title: "peninsula hotel",
    price: 23,
    category: "jaffna",
    src: "/Images/img2.jpeg",
    mapSrc: "https://goo.gl/maps/Fppi6kuCwpmPfzae6",
  },
  {
    title: "cinnamon citadel",
    price: 213,
    category: "kandy",
    src: "/Images/img3.jpeg",
    mapSrc: "https://goo.gl/maps/XLdURWYFT1ovbcjP6",
  },
  {
    title: "Lakewood residence",
    price: 213,
    category: "kandy",
    src: "/Images/img4.jpeg",
    mapSrc: "https://goo.gl/maps/1UD1LWPc3owLZQia7",
  },
  {
    title: "Royal kandyan",
    price: 213,
    category: "kandy",
    src: "/Images/img5.jpeg",
    mapSrc: "https://goo.gl/maps/4Jgmf84s9D2waG9T8",
  },
  {
    title: "ocean breeze villa",
    price: 213,
    category: "Galle",
    src: "/Images/img6.jpeg",
    mapSrc: "https://goo.gl/maps/buEu2wLNmZ1nFgYw6",
  },
  {
    title: "Arches fort",
    price: 213,
    category: "Galle",
    src: "/Images/img11.jpeg",
    mapSrc: "https://goo.gl/maps/5NTuXBGiWiUm96TdA",
  },
  {
    title: "Amari",
    price: 213,
    category: "Galle",
    src: "/Images/img5.jpeg",
    mapSrc: "https://goo.gl/maps/368LPxKEyJgafSvA7",
  },
  {
    title: "jetwing lagoon",
    price: 213,
    category: "Negombo",
    src: "/Images/img7.jpeg",
    mapSrc: "https://goo.gl/maps/DXSYr49EWccDwyDS7",
  },
  {
    title: "Amaluna resort",
    price: 213,
    category: "Negombo",
    src: "/Images/img4.jpeg",
    mapSrc: "https://goo.gl/maps/zW6oeeZE1KWr6QCK9",
  },
  {
    title: "Camelot beach hotel",
    price: 213,
    category: "Negombo",
    src: "/Images/img9.jpeg",
    mapSrc: "https://goo.gl/maps/c94po31531sonyh59",
  },
  {
    title: "the queensburry ",
    price: 213,
    category: "Nuwara Eliya",
    src: "/Images/img10.jpeg",
    mapSrc: "https://goo.gl/maps/u1aY9wAdCEUZGHfr7",
  },
  {
    title: "Hotel grand turf ",
    price: 213,
    category: "Nuwara Eliya",
    src: "/Images/img11.jpeg",
    mapSrc: "https://goo.gl/maps/1cMj2jHXeZW916FRA",
  },
  {
    title: "The golden ridge hotel",
    price: 213,
    category: "Nuwara Eliya",
    src: "/Images/img7.jpeg",
    mapSrc: "https://goo.gl/maps/ujVGXuJnep7qiLRPA",
  },
  {
    title: "Isi arana cco villa",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img9.jpeg",
    mapSrc: "https://goo.gl/maps/26FR8ZkbktYM7gkY8",
  },
  {
    title: "heritage hotel ",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img3.jpeg",
    mapSrc: "https://goo.gl/maps/TnZQ6wCUWKZaA1ec9",
  },
  {
    title: "Miridiya lake resort",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img5.jpeg",
    mapSrc: "https://goo.gl/maps/dmdCZZvEezb2xbWN7",
  },
  {
    title: "Salubrious resort",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img2.jpeg",
    mapSrc: "https://goo.gl/maps/UeR2HrT4geHDmADv7",
  },
  {
    title: "Juliana hotel",
    price: 213,
    category: "Colombo",
    src: "/Images/img8.jpeg",
    mapSrc: "https://goo.gl/maps/NaiVqkT1dGiMBanPA",
  },
  {
    title: "Radisson hotel ",
    price: 213,
    category: "Colombo",
    src: "/Images/img6.jpeg",
    mapSrc: "https://goo.gl/maps/99cCbB82ahDzb31NA",
  },
  {
    title: "grand oriental hotel",
    price: 213,
    category: "Colombo",
    src: "/Images/img4.jpeg",
    mapSrc: "https://goo.gl/maps/95bKgn384BpwPEEaA",
  },
  {
    title: "Ariyawan hotel",
    price: 213,
    category: "Ampara",
    src: "/Images/img4.jpeg",
    mapSrc: "https://goo.gl/maps/mTcNdCrfyw4QNucY9",
  },
  {
    title: "Monty hotel",
    price: 213,
    category: "Ampara",
    src: "/Images/img6.jpeg",
    mapSrc: "https://goo.gl/maps/CdGij9Axm6WV7Cgn6",
  },
  {
    title: "Terral hotel",
    price: 213,
    category: "Ampara",
    src: "/Images/img11.jpeg",
    mapSrc: "https://goo.gl/maps/Ts3hpxKSYNwsAYpT7",
  },
];

export default Categories;
