const Categories = [
  {
    title: "valampuri hotel",
    price: 23,
    category: "jaffna",
    src: "/Images/hotel1.jpg",
  },
  {
    title: "north gate hotel",
    price: 23,
    category: "jaffna",
    src: "/Images/img11.jpeg",
  },
  {
    title: "peninsula hotel",
    price: 23,
    category: "jaffna",
    src: "/Images/img2.jpeg",
  },
  {
    title: "cinnamon citadel",
    price: 213,
    category: "kandy",
    src: "/Images/img3.jpeg",
  },
  {
    title: "Lakewood residence",
    price: 213,
    category: "kandy",
    src: "/Images/img4.jpeg",
  },
  {
    title: "Royal kandyan",
    price: 213,
    category: "kandy",
    src: "/Images/img5.jpeg",
  },
  {
    title: "ocean breeze villa",
    price: 213,
    category: "Galle",
    src: "/Images/img6.jpeg",
  },
  {
    title: "Arches fort",
    price: 213,
    category: "Galle",
    src: "/Images/img11.jpeg",
  },
  {
    title: "Amari",
    price: 213,
    category: "Galle",
    src: "/Images/img5.jpeg",
  },
  {
    title: "jetwing lagoon",
    price: 213,
    category: "Negombo",
    src: "/Images/img7.jpeg",
  },
  {
    title: "Amaluna resort",
    price: 213,
    category: "Negombo",
    src: "/Images/img4.jpeg",
  },
  {
    title: "Camelot beach hotel",
    price: 213,
    category: "Negombo",
    src: "/Images/img9.jpeg",
  },
  {
    title: "the queensburry ",
    price: 213,
    category: "Nuwara Eliya",
    src: "/Images/img10.jpeg",
  },
  {
    title: "Hotel grand turf ",
    price: 213,
    category: "Nuwara Eliya",
    src: "/Images/img11.jpeg",
  },
  {
    title: "The golden ridge hotel",
    price: 213,
    category: "Nuwara Eliya",
    src: "/Images/img7.jpeg",
  },
  {
    title: "The golden ridge hotel",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img9.jpeg",
  },
  {
    title: "heritage hotel ",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img3.jpeg",
  },
  {
    title: "Miridiya lake resort",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img5.jpeg",
  },
  {
    title: "Salubrious resort",
    price: 213,
    category: "Anuradhapura",
    src: "/Images/img2.jpeg",
  },
  {
    title: "Juliana hotel",
    price: 213,
    category: "Colombo",
    src: "/Images/img8.jpeg",
  },
  {
    title: "Radisson hotel ",
    price: 213,
    category: "Colombo",
    src: "/Images/img6.jpeg",
  },
  {
    title: "grand oriental hotel",
    price: 213,
    category: "Colombo",
    src: "/Images/img4.jpeg",
  },
];

export default Categories;
